import type { ProjectModel } from "../schema/project.schema.js";
import type { StateModel } from "../schema/state.schema.js";
import { WORK_UNIT_STATUSES, workUnitCountsByStatus } from "../workflow/statuses.js";
import type { ReviewResult } from "./review-service.js";

const GENERATED_FILE_HEADER =
  "<!-- Generated by AIQT. Do not edit as source of truth. -->\n" +
  "<!-- Source of truth: .aiqt/project.json and .aiqt/state.json -->";

function bulletList(items: readonly string[]): string {
  if (items.length === 0) return "- None.";
  return items.map((item) => `- ${item}`).join("\n");
}

function orNone(value: string | null | undefined): string {
  return value && value.trim() !== "" ? value : "(none)";
}

// ---------------------------------------------------------------------------
// project-plan.md
// ---------------------------------------------------------------------------

export function renderProjectPlan(project: ProjectModel, state: StateModel): string {
  const lines: string[] = [];
  lines.push(GENERATED_FILE_HEADER, "");
  lines.push("# AIQT Project Plan", "");

  lines.push("## Project Objective", "");
  lines.push(orNone(project.project.objective), "");

  lines.push("## Target Users", "");
  lines.push(bulletList(project.project.targetUsers), "");

  lines.push("## Requirements", "");
  lines.push(
    project.requirements.length > 0
      ? project.requirements
          .map((r) => `- [${r.id}] ${r.title} - ${r.description} (${r.status})`)
          .join("\n")
      : "- None.",
    "",
  );

  lines.push("## Constraints", "");
  lines.push(bulletList(project.context.constraints), "");

  lines.push("## Non-Goals", "");
  lines.push(bulletList(project.context.nonGoals), "");

  lines.push("## Open Questions", "");
  lines.push(
    project.openQuestions.length > 0
      ? project.openQuestions
          .map((q) => `- [${q.id}] ${q.question} (impact: ${q.impact}, status: ${q.status})`)
          .join("\n")
      : "- None.",
    "",
  );

  lines.push("## Milestones", "");
  lines.push(
    state.workGraph.milestones.length > 0
      ? state.workGraph.milestones
          .map((m) => `- [${m.id}] ${m.title} - ${m.status}`)
          .join("\n")
      : "- None.",
    "",
  );

  lines.push("## Work Units", "");
  lines.push(
    state.workGraph.workUnits.length > 0
      ? state.workGraph.workUnits
          .map((wu) => `- [${wu.id}] ${wu.title} - ${wu.status} (milestone: ${wu.milestoneId})`)
          .join("\n")
      : "- None.",
    "",
  );

  lines.push("## Dependencies", "");
  lines.push(
    state.workGraph.dependencies.length > 0
      ? state.workGraph.dependencies
          .map((d) => `- [${d.id}] ${d.type}: ${d.fromId} -> ${d.toId}`)
          .join("\n")
      : "- None.",
    "",
  );

  lines.push("## Next Recommended Command", "");
  lines.push(orNone(state.nextRecommendedCommand));

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// status-report.md
// ---------------------------------------------------------------------------

export function renderStatusReport(
  project: ProjectModel,
  state: StateModel,
  review: ReviewResult,
): string {
  const lines: string[] = [];
  lines.push(GENERATED_FILE_HEADER, "");
  lines.push("# AIQT Status Report", "");

  lines.push("## Project", "");
  lines.push(`- Name: ${project.project.name}`);
  lines.push(`- Objective: ${orNone(project.project.objective)}`);
  lines.push(`- Status: ${state.projectStatus}`, "");

  lines.push("## Current Workflow Position", "");
  lines.push(`- Current milestone: ${state.currentMilestoneId ?? "None"}`);
  lines.push(`- Current work unit: ${state.currentWorkUnitId ?? "None"}`);
  lines.push(`- Next recommended command: ${orNone(state.nextRecommendedCommand)}`, "");

  lines.push("## Work Unit Counts", "");
  const counts = workUnitCountsByStatus(state);
  lines.push(WORK_UNIT_STATUSES.map((s) => `- ${s}: ${counts[s]}`).join("\n"), "");

  lines.push("## Milestones Table", "");
  lines.push("| ID | Title | Status | Work Units |");
  lines.push("| --- | --- | --- | --- |");
  for (const m of state.workGraph.milestones) {
    lines.push(`| ${m.id} | ${m.title} | ${m.status} | ${m.workUnitIds.join(", ") || "-"} |`);
  }
  lines.push("");

  lines.push("## Work Units Table", "");
  lines.push("| ID | Milestone | Title | Status | Dependencies |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const wu of state.workGraph.workUnits) {
    lines.push(
      `| ${wu.id} | ${wu.milestoneId} | ${wu.title} | ${wu.status} | ${wu.dependencies.join(", ") || "-"} |`,
    );
  }
  lines.push("");

  lines.push("## Checkpoints Summary", "");
  lines.push(`- Checkpoints: ${state.checkpoints.length}`, "");

  lines.push("## Findings Summary", "");
  lines.push(`- Blocking findings: ${review.blockingFindingCount}`);
  lines.push(`- Non-blocking findings: ${review.findingCount - review.blockingFindingCount}`);

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// technical-spec.md
// ---------------------------------------------------------------------------

export function renderTechnicalSpec(project: ProjectModel, state: StateModel): string {
  const lines: string[] = [];
  lines.push(GENERATED_FILE_HEADER, "");
  lines.push("# AIQT Technical Specification Export", "");

  lines.push("## Technical Overview", "");
  lines.push(orNone(project.project.objective), "");

  lines.push("## Architecture Notes", "");
  lines.push(bulletList(project.context.architectureNotes), "");

  lines.push("## Technology Preferences", "");
  lines.push(bulletList(project.context.technologyPreferences), "");

  lines.push("## Business Rules", "");
  lines.push(bulletList(project.context.businessRules), "");

  lines.push("## Constraints", "");
  lines.push(bulletList(project.context.constraints), "");

  lines.push("## Quality Expectations", "");
  lines.push(
    `- Acceptance criteria required: ${project.quality.acceptanceCriteriaRequired ? "yes" : "no"}`,
  );
  lines.push(
    `- Validation required before done: ${project.quality.validationRequiredBeforeDone ? "yes" : "no"}`,
  );
  lines.push("- Preferred validation commands:");
  lines.push(bulletList(project.quality.preferredValidationCommands), "");

  lines.push("## Work Graph Implementation Plan", "");
  lines.push(
    state.workGraph.milestones.length > 0
      ? state.workGraph.milestones
          .map((m) => `- [${m.id}] ${m.title}: ${m.workUnitIds.join(", ") || "no work units"}`)
          .join("\n")
      : "- None.",
    "",
  );

  lines.push("## Validation Expectations", "");
  const validationCommands = [
    ...new Set(state.workGraph.workUnits.flatMap((wu) => wu.validationCommands)),
  ];
  lines.push(
    validationCommands.length > 0
      ? bulletList(validationCommands)
      : bulletList(project.quality.preferredValidationCommands),
    "",
  );

  lines.push("## Suggested Files / Areas", "");
  const suggestedFiles = [
    ...new Set(state.workGraph.workUnits.flatMap((wu) => wu.suggestedFiles)),
  ];
  lines.push(bulletList(suggestedFiles));

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// agent-packet-<packetId>.md
// ---------------------------------------------------------------------------

export function renderAgentPacketExport(state: StateModel): string {
  const packet = state.lastAgentPacket;
  const lines: string[] = [];
  lines.push(GENERATED_FILE_HEADER, "");
  lines.push("# AIQT Agent Packet Export", "");
  lines.push(`Packet ID: ${packet?.id ?? "(none)"}`);
  lines.push(`Work Unit ID: ${packet?.workUnitId ?? "(none)"}`);
  lines.push(`Milestone ID: ${packet?.milestoneId ?? "(none)"}`);
  lines.push(`Created At: ${packet?.createdAt ?? "(none)"}`);
  lines.push(`Content Hash: ${packet?.contentHash ?? "(none)"}`, "");
  lines.push(
    "This export records packet metadata only unless the implementation stores packet text in state.",
  );
  lines.push("M6 must not invent packet text that is not available from canonical state.");

  return lines.join("\n");
}
